version: "3.9"
services:
  hotel-db:
    container_name: hotel-db
    restart: always
    image: mongo:6.0.2
    volumes:
      - ./.database/mongodb:/data/db
    environment:
        - MONGO_INITDB_DATABASE=booking_db
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=qwerty
    ports:
      - "27017:27017"