version: "3.9"
services:
  postgres-db:
    restart: always
    image: postgres:13.3
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "booking-agent-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5436:5432"